import {LanguageId} from "src/main";

export const DISPLAY_NAMES: Record<LanguageId, string> = {
    cpp: "C++",
    cs: "C#",
    go: "Golang",
    groovy: "Groovy",
    haskell: "Haskell",
    java: "Java",
    js: "Javascript",
    kotlin: "Kotlin",
    latex: "LaTeX",
    lua: "Lua",
    mathematica: "Mathematica",
    php: "PHP",
    powershell: "Powershell",
    prolog: "Prolog",
    python: "Python",
    r: "R",
	rust: "Rust",
	shell: "Shell",
	batch: "Batch",
	ts: "Typescript",
	scala: "Scala",
    swift: "Swift",
	racket: "Racket",
	c: "C",
	fsharp: "F#",
	ruby: "Ruby",
	dart: "Dart",
	lean: "Lean",
	sql: "SQL",
	octave: "Octave",
	maxima: "Maxima",
    applescript: "Applescript",
	zig: "Zig",
	ocaml: "OCaml",
} as const;
