import { LanguageId } from "src/main";

export const DISPLAY_NAMES: Record<LanguageId, string> = {
    cpp: "C++",
    cs: "C#",
    dart: "Dart",
    go: "Golang",
    groovy: "Groovy",
    haskell: "Haskell",
    java: "Java",
    js: "Javascript",
    kotlin: "Kotlin",
    lean: "Lean",
    lua: "Lua",
    mathematica: "Mathematica",
    powershell: "Powershell",
    prolog: "Prolog",
    python: "Python",
    r: "R",
    rust: "Rust",
    shell: "Shell",
    ts: "Typescript",
    scala: "Scala",
    racket: "Racket",
    c: "C",
    fsharp: "F#",
} as const;
